### ISSUE TITLE
More Characters

### ISSUE THREAD

**Issue by ghost** [Quorafind/obsidian-sakana-widget#1]
**Hey Bro can you add more characters or allow an option to add our own characters**

**Comment by adrianofontanari** [comment]
+ 1 I modified the main.js file and added my images. I would like to retain them otherwise they would be deleted after every update (I would need to copy and paste manually the code).

**Comment by ghost** [comment]
> * 1 I modified the main.js file and added my images. I would like to retain them otherwise they would be deleted after every update (I would need to copy and paste manually the code).

Can you share the js file, i am getting error when loading the widget

**Comment by Quorafind** [comment]
@tecnoborder @joyskmathew Now you can add your own character in settings.

**Comment by ghost** [comment]
Bro, can you explain the steps to add the characters?

I tried but the png character's background is not blurring, a square box is coming as the background
