### ISSUE TITLE
Obsidian 16.4 insider - fail to unload widget

### ISSUE THREAD

**Issue by adrianofontanari** [Quorafind/obsidian-sakana-widget#2]
I have an Obsidian 16.4 build. When I try to disable the widget, I get an error message + when I reload it, it works but it is frozen (the widget  does not move). I need to close and re-open obsidian

**Comment by Quorafind** [comment]
Are you in v1.1.0 ?

**Comment by adrianofontanari** [comment]
<img width="666" alt="Screenshot 2022-10-15 at 17 33 56" src="https://user-images.githubusercontent.com/18950662/195994965-f60d3079-c8a2-426c-9452-547ac22cdb7e.png">

**Comment by adrianofontanari** [comment]
sorry I mean 1.0, before I had an insider build

**Comment by adrianofontanari** [comment]
BTW, thank so so much for the Sakana widget. It is just amazing. For example, I could add my childhood dog in Obsidian!

**Comment by Quorafind** [comment]
> <img alt="Screenshot 2022-10-15 at 17 33 56" width="666" src="https://user-images.githubusercontent.com/18950662/195994965-f60d3079-c8a2-426c-9452-547ac22cdb7e.png">

Sorry, I was asking the sakana widget plugin version.

**Comment by tecnoborder** [comment]
Sorry I had probably an older version. I deleted and reinstalled the plugin and I can enable/disable it without problems. Thank you for the prompt reply!

**Comment by adrianofontanari** [comment]
Yeah 1.1

**Comment by adrianofontanari** [comment]
so If I close the widget from the close button, then I go to the obsidian settings and disable it and re-enable the widget, I got the error message

**Comment by adrianofontanari** [comment]
It coulld be great to have a command to enable the widget once closed

**Comment by Quorafind** [comment]
> so If I close the widget from the close button, then I go to the obsidian settings and disable it and re-enable the widget, I got the error message

Thanks for this, I will fix it soon.

**Comment by Quorafind** [comment]
Try again with 2.0.0, it should be fixed

**Comment by adrianofontanari** [comment]
cool! thanks for the update. Unfortunately I am unable to update it
