### ISSUE TITLE
Failed to install Sakana 2.0

### ISSUE THREAD

**Issue by adrianofontanari** [Quorafind/obsidian-sakana-widget#6]
Hello there,
I am unable to install sakana. I tried to update and it did not work, I uninstalled it and tried to install it (after restarting the mac) and it did not work too

<img width="283" alt="Screenshot 2022-10-29 at 10 55 56" src="https://user-images.githubusercontent.com/18950662/198822912-6d0d5ba7-c8fc-423f-ac40-733a08299f03.png">

**Comment by Quorafind** [comment]
try again with 2.0.3

**Comment by adrianofontanari** [comment]
<img width="408" alt="Screenshot 2022-10-29 at 11 13 15" src="https://user-images.githubusercontent.com/18950662/198823545-ce2130eb-f1f5-44d0-b3ce-287169ad96ad.png">
Installed correctly but I have a problem in opening it

**Comment by Quorafind** [comment]
I am working at this. just wait a minute

**Comment by Quorafind** [comment]
Try again please. @tecnoborder

**Comment by adrianofontanari** [comment]
it works thank you so much for the great work!! For the future, would it be possible to:
- set a new widget as the default one when I open the app?
- use a local picture?

**Comment by Quorafind** [comment]
the first is done in this version.
the second would be added in next version

**Comment by adrianofontanari** [comment]
nice I added a local Image in my vault but I got this
<img width="4" alt="Screenshot 2022-10-29 at 11 31 44" src="https://user-images.githubusercontent.com/18950662/198824381-a71d2a00-f3fe-4c9a-8f84-efcdb37c8bdf.png">

<img width="137" alt="Screenshot 2022-10-29 at 11 31 54" src="https://user-images.githubusercontent.com/18950662/198824377-c32a6015-59ea-4437-8beb-383c094a5064.png">

**Comment by adrianofontanari** [comment]
the url is: /Users/myaccount/Library/Mobile\ Documents/iCloud\~md\~obsidian/Documents/Notes/image.png

**Comment by Quorafind** [comment]
@tecnoborder I think it is hard to add image that isn't in vault. Seems like this image you added is in Obsidian vault?

**Comment by adrianofontanari** [comment]
Yes My vault is the folder Notes

**Comment by adrianofontanari** [comment]
so I added the picture in the root path of my Obsidian Vault

**Comment by Quorafind** [comment]
Now you can add your image name as url: like `Pasted Image 20220418134410.png`

**Comment by adrianofontanari** [comment]
Hello Quorafind! I did not get how to add an image as: a Pasted Image e.g. Pasted Image 20220418134410.png. I did several attempts but could not find a way. Could you kindly explain how to do so? thank you!

**Comment by adrianofontanari** [comment]
One more thing: could you add a command to open specific characters or re-open the widget (instead of closing obsidian or disabling/re-enabling it)
